# Generated by Django 5.2.8 on 2025-11-27 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_order_order_status'),
        ('user', '0003_order_razorpay_order_id_order_razorpay_payment_id_and_more'),
    ]

    operations = [
    ]
